name: Check
on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check building success
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pnpm install
      - name: Build project
        run: pnpm run build